"use client"

import { useEffect, useState } from "react"
import { Download, FileCheck2, FileText, Printer } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { readStoredScreeningResult } from "@/lib/screening-result"

type ScreeningResult = {
  metadata?: { patient_id?: string | null; generated_at?: string; run_id?: string }
  quality?: { status?: string }
  prediction?: { class_name?: string | null; confidence?: number | null; status?: string }
  uncertainty?: { manual_review?: boolean; entropy?: number | null; margin?: number | null }
  recommendation?: { urgency?: string; text?: string }
  outputs?: { report_url?: string | null; explanation_url?: string | null }
}

export default function ReportsPage() {
  const [result, setResult] = useState<ScreeningResult | null>(null)

  useEffect(() => {
    const update = () => setResult(readStoredScreeningResult<ScreeningResult>())
    update()
    window.addEventListener("storage", update)
    window.addEventListener("retinaai-last-screening-updated", update)
    return () => {
      window.removeEventListener("storage", update)
      window.removeEventListener("retinaai-last-screening-updated", update)
    }
  }, [])

  const reportRows = [
    ["Patient ID", result?.metadata?.patient_id || "Unspecified"],
    ["Date", result?.metadata?.generated_at || "not available"],
    ["Quality", result?.quality?.status || "not available"],
    ["Prediction", result?.prediction?.class_name || result?.prediction?.status || "not available"],
    ["Confidence", typeof result?.prediction?.confidence === "number" ? `${Math.round(result.prediction.confidence * 100)}%` : "not available"],
    ["Uncertainty", result ? `Entropy ${result.uncertainty?.entropy ?? "n/a"} / Margin ${result.uncertainty?.margin ?? "n/a"}` : "not available"],
  ]

  return (
    <AppShell>
      <PageHeader
        eyebrow="Reports"
        title="Clinical handoff report"
        description="Review and open the hospital-style PDF generated by the screening pipeline with disclaimer, Grad-CAM artifact, quality metrics, uncertainty, and recommendation."
        action={result?.outputs?.report_url ? <Button asChild><a href={result.outputs.report_url} target="_blank"><Download className="h-4 w-4" /> Open PDF</a></Button> : undefined}
      />

      <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
        <Card className="medical-glass p-3 sm:p-6">
          <div className="mx-auto max-w-3xl rounded-lg border bg-white p-6 text-slate-950 shadow-sm sm:p-10">
            <div className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="flex items-center gap-2 text-sm font-semibold text-blue-700">
                  <FileCheck2 className="h-4 w-4" /> RetinaAI Screening Report
                </div>
                <h2 className="mt-4 text-3xl font-semibold text-slate-950">Retinal screening support summary</h2>
                <p className="mt-3 text-sm leading-6 text-slate-600">Prototype output for qualified clinical review. This report is not a clinical diagnosis.</p>
              </div>
              <Badge variant={result ? "teal" : "slate"} className="bg-slate-100 text-slate-700">{result ? "Generated" : "Awaiting upload"}</Badge>
            </div>

            <div className="mt-8 grid gap-3 sm:grid-cols-2">
              {reportRows.map(([label, value]) => (
                <div key={label} className="rounded-lg border border-slate-200 p-4">
                  <p className="text-xs uppercase text-slate-500">{label}</p>
                  <p className="mt-2 text-sm font-semibold text-slate-950">{value}</p>
                </div>
              ))}
            </div>

            <div className="mt-8 rounded-lg bg-slate-50 p-5">
              <h3 className="font-semibold text-slate-950">Recommendation</h3>
              <p className="mt-3 text-sm leading-7 text-slate-600">
                {result?.recommendation?.text || "Upload an image to generate report recommendations and artifact links from the API."}
              </p>
            </div>
          </div>
        </Card>

        <aside className="space-y-6">
          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Report actions</CardTitle>
              <CardDescription>Available once a connected screening run creates a PDF.</CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3">
              {result?.outputs?.report_url ? <Button asChild variant="outline" className="justify-start"><a href={result.outputs.report_url} target="_blank"><FileText className="h-4 w-4" /> Open generated PDF</a></Button> : null}
              <Button variant="outline" className="justify-start" disabled={!result}><Printer className="h-4 w-4" /> Print packet</Button>
            </CardContent>
          </Card>

          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Compliance frame</CardTitle>
              <CardDescription>Report language avoids unsafe diagnostic claims.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Screening prototype only.</p>
              <p>Rejects low-quality inputs before prediction.</p>
              <p>Routes uncertain cases to manual review.</p>
            </CardContent>
          </Card>
        </aside>
      </div>
    </AppShell>
  )
}