"use client"

import Image from "next/image"
import { useEffect, useState } from "react"
import { Eye, Layers, Maximize2 } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { ConfidenceGauge } from "@/components/confidence-gauge"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

type ScreeningResult = {
  prediction?: { class_name?: string | null; confidence?: number | null }
  uncertainty?: { manual_review?: boolean; reason?: string; entropy?: number | null; margin?: number | null }
  outputs?: { explanation_url?: string | null; gradcam_url?: string | null }
}

function readLast(): ScreeningResult | null {
  try {
    const stored = window.localStorage.getItem("retinaai-last-screening")
    return stored ? JSON.parse(stored) as ScreeningResult : null
  } catch {
    return null
  }
}

export default function GradCamPage() {
  const [result, setResult] = useState<ScreeningResult | null>(null)

  useEffect(() => {
    const update = () => setResult(readLast())
    update()
    window.addEventListener("storage", update)
    window.addEventListener("retinaai-last-screening-updated", update)
    return () => {
      window.removeEventListener("storage", update)
      window.removeEventListener("retinaai-last-screening-updated", update)
    }
  }, [])

  const gradcamUrl = result?.outputs?.gradcam_url || result?.outputs?.explanation_url

  return (
    <AppShell>
      <PageHeader
        eyebrow="Grad-CAM viewer"
        title="Explainability artifact"
        description="Inspect the Grad-CAM overlay generated by the CNN pipeline. If the model falls back to the random forest baseline, the artifact states that CNN Grad-CAM is unavailable."
        action={gradcamUrl ? <Button asChild variant="outline"><a href={gradcamUrl} target="_blank"><Maximize2 className="h-4 w-4" /> Open artifact</a></Button> : undefined}
      />

      <div className="grid gap-6 xl:grid-cols-[1fr_380px]">
        <Card className="medical-glass overflow-hidden">
          <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <CardTitle>Fundus scan overlay</CardTitle>
              <CardDescription>Generated artifact from the latest connected screening run.</CardDescription>
            </div>
            <Badge variant={gradcamUrl ? "teal" : "slate"}>{gradcamUrl ? "Available" : "Awaiting screening"}</Badge>
          </CardHeader>
          <CardContent>
            <div className="relative mx-auto grid aspect-[16/10] max-w-4xl place-items-center overflow-hidden rounded-lg border bg-muted">
              {gradcamUrl ? (
                <Image src={gradcamUrl} alt="Generated Grad-CAM overlay" fill className="object-contain" unoptimized />
              ) : (
                <div className="p-8 text-center text-sm text-muted-foreground">
                  <Layers className="mx-auto mb-3 h-8 w-8 text-secondary" />
                  Run a screening from Upload to generate a Grad-CAM or unavailable-explanation artifact.
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        <aside className="space-y-6">
          <ConfidenceGauge
            label={result?.prediction?.class_name || "No screening loaded"}
            value={typeof result?.prediction?.confidence === "number" ? Math.round(result.prediction.confidence * 100) : 0}
            sublabel={result?.uncertainty?.reason || "Run Upload to populate explainability context"}
            className="medical-glass"
          />

          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Artifact context</CardTitle>
              <CardDescription>Use Grad-CAM as review support, not diagnostic proof.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm">
              {[
                ["Manual review", result?.uncertainty?.manual_review ? "Required" : result ? "Not required" : "not available"],
                ["Entropy", result?.uncertainty?.entropy ?? "not available"],
                ["Top-2 margin", result?.uncertainty?.margin ?? "not available"],
              ].map(([label, value]) => (
                <div key={label} className="flex items-center justify-between rounded-lg border bg-card p-3">
                  <span className="flex items-center gap-2 text-muted-foreground"><Eye className="h-4 w-4 text-secondary" /> {label}</span>
                  <span className="font-medium text-foreground">{String(value)}</span>
                </div>
              ))}
            </CardContent>
          </Card>
        </aside>
      </div>
    </AppShell>
  )
}