"use client"

import { motion } from "framer-motion"
import { CheckCircle2, Lock, ShieldAlert } from "lucide-react"
import { AnalysisUploader } from "@/components/analysis-uploader"
import { AppShell } from "@/components/app-shell"
import { PageHeader } from "@/components/page-header"
import { TremorProgress } from "@/components/tremor-progress"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"

const qualityChecks = [
  { label: "Field of view", value: 96 },
  { label: "Illumination", value: 91 },
  { label: "Focus sharpness", value: 88 },
  { label: "Artifact risk", value: 12 },
]

const uploadSteps = [
  { title: "Upload", copy: "Encrypted local intake", icon: CheckCircle2 },
  { title: "Quality", copy: "No blind prediction", icon: ShieldAlert },
  { title: "Inference", copy: "Manual-review aware", icon: CheckCircle2 },
]

export default function UploadPage() {
  return (
    <AppShell>
      <PageHeader
        eyebrow="Upload"
        title="Start a retinal screening review"
        description="Upload fundus images, run quality checks, and route poor inputs to manual review before inference. Results are generated by the shared RetinaAI inference pipeline."
        action={<Button variant="outline"><Lock className="h-4 w-4" /> Safety-first workflow</Button>}
      />

      <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
        <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }}>
          <Card className="medical-glass overflow-hidden">
            <CardContent className="p-0">
              <div className="grid min-h-[520px] place-items-center border-b bg-muted/35 p-6 text-center sm:p-10">
                <AnalysisUploader />
              </div>
              <div className="grid gap-4 p-6 md:grid-cols-3">
                {uploadSteps.map((step) => (
                  <div key={step.title} className="rounded-lg border bg-card p-4">
                    <step.icon className="h-5 w-5 text-secondary" />
                    <p className="mt-3 text-sm font-medium text-foreground">{step.title}</p>
                    <p className="mt-1 text-xs text-muted-foreground">{step.copy}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.section>

        <aside className="space-y-6">
          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Quality gate</CardTitle>
              <CardDescription>Pre-inference screening checks for image reliability.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-5">
              {qualityChecks.map((check) => (
                <div key={check.label}>
                  <div className="mb-2 flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">{check.label}</span>
                    <span className="font-medium text-foreground">{check.value}%</span>
                  </div>
                  <Progress value={check.value} />
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Screening readiness</CardTitle>
              <CardDescription>Current intake queue and manual-review status.</CardDescription>
            </CardHeader>
            <CardContent>
              <TremorProgress value={82} />
              <div className="mt-4 grid grid-cols-2 gap-3 text-sm">
                <div className="rounded-lg border bg-card p-3">
                  <p className="text-muted-foreground">Queue</p>
                  <p className="mt-1 text-xl font-semibold text-foreground">12</p>
                </div>
                <div className="rounded-lg border bg-card p-3">
                  <p className="text-muted-foreground">Manual review</p>
                  <p className="mt-1 text-xl font-semibold text-foreground">3</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </aside>
      </div>
    </AppShell>
  )
}
