"use client"

import { motion } from "framer-motion"
import { CheckCircle2, Lock, Server, ShieldAlert } from "lucide-react"
import { AnalysisUploader } from "@/components/analysis-uploader"
import { AppShell } from "@/components/app-shell"
import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

const uploadSteps = [
  { title: "Upload", copy: "Browser file selection", icon: CheckCircle2 },
  { title: "Quality", copy: "Returned by API", icon: ShieldAlert },
  { title: "Inference", copy: "Connected backend only", icon: Server },
]

export default function UploadPage() {
  return (
    <AppShell>
      <PageHeader
        eyebrow="Upload"
        title="Start a retinal screening review"
        description="Upload fundus images, run quality checks, and route poor inputs to manual review before inference. Results are generated by the shared RetinaAI inference pipeline."
        action={<Button variant="outline"><Lock className="h-4 w-4" /> Safety-first workflow</Button>}
      />

      <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
        <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }}>
          <Card className="medical-glass overflow-hidden">
            <CardContent className="p-0">
              <div className="grid min-h-[520px] place-items-center border-b bg-muted/35 p-6 text-center sm:p-10">
                <AnalysisUploader />
              </div>
              <div className="grid gap-4 p-6 md:grid-cols-3">
                {uploadSteps.map((step) => (
                  <div key={step.title} className="rounded-lg border bg-card p-4">
                    <step.icon className="h-5 w-5 text-secondary" />
                    <p className="mt-3 text-sm font-medium text-foreground">{step.title}</p>
                    <p className="mt-1 text-xs text-muted-foreground">{step.copy}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.section>

        <aside className="space-y-6">
          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Runtime quality metrics</CardTitle>
              <CardDescription>Scores appear only after the backend processes an uploaded image.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Blur, brightness, contrast, and retina visibility are returned by FastAPI.</p>
              <p>No quality score is estimated in the frontend.</p>
            </CardContent>
          </Card>

          <Card className="medical-glass">
            <CardHeader>
              <CardTitle>Backend requirement</CardTitle>
              <CardDescription>The deployed frontend needs a reachable RetinaAI API URL.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>Local development defaults to `http://127.0.0.1:8000`.</p>
              <p>Vercel previews require `RETINAAI_API_URL`; otherwise uploads fail with a configuration error.</p>
            </CardContent>
          </Card>
        </aside>
      </div>
    </AppShell>
  )
}